# Build-time antialiased glyph atlas for XaAES render_apj.
# Monospace, cell-fitted: the advance is exactly the system font's cell
# width, so legacy dialog layout (8x16 character cells) is untouched.
from PIL import Image, ImageFont, ImageDraw
import sys

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
CELLS = [(8,16), (9,18), (10,20), (11,22), (12,24), (13,26), (14,28), (16,32)]
FIRST, LAST = 32, 126
# Atari ST charset extras the desktop uses, as (atari_code, unicode) pairs.
# They are appended after 126 in the atlas; the C side maps code -> slot.
EXTRA = [(0xF8, 0x00B0),   # degree sign
         (0xB0, 0x00E3),   # a tilde
         (0xB1, 0x00F5),   # o tilde
         (0xDD, 0x00A7),   # section
         (0xDE, 0x2227),   # and
         (0xF6, 0x00F7),   # division
         (0xF7, 0x2248),   # approx
         (0xFE, 0x00B2),   # squared
         (0xFF, 0x00B3)]   # cubed

out = []
out.append("/* Generated by mkatlas.py - do not edit.\n"
           " * DejaVu Sans Mono (Bitstream Vera licence), 8-bit coverage per pixel,\n"
           " * ASCII 32..126, one glyph per system-font cell so the advance matches\n"
           " * the bitmap font exactly. */\n")
out.append("#ifndef _apj_atlas_h_\n#define _apj_atlas_h_\n\n")
out.append("struct apj_atlas { short cw, ch; const unsigned char *cov; };  /* cov[slot*ch*cw], slot = apj_atlas_slot(c) */\n\n")

names = []
for cw, ch in CELLS:
    # pick the largest pixel size whose advance fits the cell width
    size = 4
    while True:
        f = ImageFont.truetype(FONT, size + 1)
        adv = f.getlength("M")
        asc, desc = f.getmetrics()
        if adv > cw or asc + desc > ch:
            break
        size += 1
    f = ImageFont.truetype(FONT, size)
    asc, desc = f.getmetrics()
    # vertically centre the em box in the cell
    ytop = (ch - (asc + desc)) // 2
    adv = f.getlength("M")
    xoff = int(round((cw - adv) / 2))
    name = "apj_cov_%dx%d" % (cw, ch)
    names.append((cw, ch, name))
    data = bytearray()
    glyphs = [chr(c) for c in range(FIRST, LAST + 1)] + [chr(u) for a, u in EXTRA]
    for g in glyphs:
        im = Image.new("L", (cw, ch), 0)
        d = ImageDraw.Draw(im)
        d.text((xoff, ytop), g, font=f, fill=255)
        data += im.tobytes()
    out.append("static const unsigned char %s[%d] = {\n" % (name, len(data)))
    for i in range(0, len(data), 24):
        out.append("\t" + ",".join("%3d" % b for b in data[i:i+24]) + ",\n")
    out.append("};\n\n")
    print("cell %dx%d: font px %d, advance %.2f, asc+desc %d, %d bytes" % (cw, ch, size, adv, asc+desc, len(data)), file=sys.stderr)

out.append("static const struct apj_atlas apj_atlases[] = {\n")
for cw, ch, name in names:
    out.append("\t{ %d, %d, %s },\n" % (cw, ch, name))
out.append("};\n#define APJ_N_ATLASES %d\n\n" % len(names))
out.append("/* atlas slot for an Atari-charset code, -1 if not in the atlas */\n")
out.append("static short apj_atlas_slot(unsigned char c)\n{\n\tif (c >= 32 && c <= 126)\n\t\treturn c - 32;\n\tswitch (c)\n\t{\n")
for i, (a, u) in enumerate(EXTRA):
    out.append("\t\tcase 0x%02X: return %d;\n" % (a, 95 + i))
out.append("\t}\n\treturn -1;\n}\n\n#endif\n")
open("apj_atlas.h", "w").write("".join(out))
print("wrote apj_atlas.h", file=sys.stderr)
