# Build-time antialiased glyph atlas for XaAES render_apj.
# Monospace, cell-fitted: the advance is exactly the system font's cell
# width, so legacy dialog layout (8x16 character cells) is untouched.
from PIL import Image, ImageFont, ImageDraw
import sys

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
CELLS = [(8,16), (10,20), (12,24), (16,32)]
FIRST, LAST = 32, 126

out = []
out.append("/* Generated by mkatlas.py - do not edit.\n"
           " * DejaVu Sans Mono (Bitstream Vera licence), 8-bit coverage per pixel,\n"
           " * ASCII 32..126, one glyph per system-font cell so the advance matches\n"
           " * the bitmap font exactly. */\n")
out.append("#ifndef _apj_atlas_h_\n#define _apj_atlas_h_\n\n")
out.append("struct apj_atlas { short cw, ch; const unsigned char *cov; };  /* cov[(c-32)*ch*cw] */\n\n")

names = []
for cw, ch in CELLS:
    # pick the largest pixel size whose advance fits the cell width
    size = 4
    while True:
        f = ImageFont.truetype(FONT, size + 1)
        adv = f.getlength("M")
        asc, desc = f.getmetrics()
        if adv > cw or asc + desc > ch:
            break
        size += 1
    f = ImageFont.truetype(FONT, size)
    asc, desc = f.getmetrics()
    # vertically centre the em box in the cell
    ytop = (ch - (asc + desc)) // 2
    adv = f.getlength("M")
    xoff = int(round((cw - adv) / 2))
    name = "apj_cov_%dx%d" % (cw, ch)
    names.append((cw, ch, name))
    data = bytearray()
    for c in range(FIRST, LAST + 1):
        im = Image.new("L", (cw, ch), 0)
        d = ImageDraw.Draw(im)
        d.text((xoff, ytop), chr(c), font=f, fill=255)
        data += im.tobytes()
    out.append("static const unsigned char %s[%d] = {\n" % (name, len(data)))
    for i in range(0, len(data), 24):
        out.append("\t" + ",".join("%3d" % b for b in data[i:i+24]) + ",\n")
    out.append("};\n\n")
    print("cell %dx%d: font px %d, advance %.2f, asc+desc %d, %d bytes" % (cw, ch, size, adv, asc+desc, len(data)), file=sys.stderr)

out.append("static const struct apj_atlas apj_atlases[] = {\n")
for cw, ch, name in names:
    out.append("\t{ %d, %d, %s },\n" % (cw, ch, name))
out.append("};\n#define APJ_N_ATLASES %d\n\n#endif\n" % len(names))
open("apj_atlas.h", "w").write("".join(out))
print("wrote apj_atlas.h", file=sys.stderr)
